// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "Obsidian Black, 12GB RAM, flagship Google Tensor G2 processor, unmatched camera quality.",
                            ImageUrl = "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?w=500",
                            Name = "Google Pixel 7 Pro (128GB)",
                            Price = 145000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Industry-leading noise canceling overhead wireless headphones with 30 hours battery life.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
                            Name = "Sony WH-1000XM4 Headphones",
                            Price = 78000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Description = "Ultra-high capacity 20000mAh external battery pack with high-speed PowerIQ technology.",
                            ImageUrl = "https://images.unsplash.com/photo-1609592424085-78e7343bc8f1?w=500",
                            Name = "Anker PowerCore 20K Power Bank",
                            Price = 8500m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            Description = "Blue switches tactical mechanical keyboard with customizable multi-color RGB backlighting.",
                            ImageUrl = "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=500",
                            Name = "Mechanical RGB Gaming Keyboard",
                            Price = 6500m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            Description = "LIGHTSPEED wireless gaming mouse featuring the next-gen HERO sensor with 12,000 DPI.",
                            ImageUrl = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500",
                            Name = "Logitech G305 Wireless Mouse",
                            Price = 9200m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Description = "Liquid Retina display, powerful Apple M2 chip, 128GB storage, supports Apple Pencil.",
                            ImageUrl = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500",
                            Name = "iPad Pro 11-inch M2 (WiFi)",
                            Price = 245000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            Description = "Premium 4K USB-C hub monitor with brilliant color coverage and height adjustable stand.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
                            Name = "Dell UltraSharp 27\" 4K Monitor",
                            Price = 115000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Description = "IP67 waterproof and dustproof portable Bluetooth speaker with powerful two-way sound system.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
                            Name = "JBL Flip 6 Portable BT Speaker",
                            Price = 32000m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            Description = "Incredible performance with read speeds up to 1050MB/s, works with PC, Mac, and Android.",
                            ImageUrl = "https://images.unsplash.com/photo-1601524909162-be87252be298?w=500",
                            Name = "Crucial X8 1TB Portable SSD",
                            Price = 24000m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Electronics",
                            Description = "Custom-tuned 50mm drivers with cooling gel cushions and retractable noise-isolating mic.",
                            ImageUrl = "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500",
                            Name = "Razer Kraken Gaming Headset",
                            Price = 18500m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Watches",
                            Description = "Swiss quartz chronograph movement timepiece with a premium dark brown leather strap.",
                            ImageUrl = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
                            Name = "Tissot Chrono XL Classic Watch",
                            Price = 98000m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Watches",
                            Description = "Solid stainless steel build, automatic self-winding movement, 100m water resistance.",
                            ImageUrl = "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=500",
                            Name = "Seiko 5 Sports Automatic Watch",
                            Price = 64000m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Watches",
                            Description = "Iconic retro digital styling, gold-plated mesh band, built-in stopwatch and daily alarm.",
                            ImageUrl = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=500",
                            Name = "Casio Vintage Digital Gold Watch",
                            Price = 12500m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Watches",
                            Description = "Premium smart watch with rotating bezel, advanced fitness tracking, and AMOLED screen.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500",
                            Name = "Samsung Galaxy Watch 6 Classic",
                            Price = 72000m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Watches",
                            Description = "Ultra-thin luxury minimalist watch with a stealthy black dial and stainless steel mesh band.",
                            ImageUrl = "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=500",
                            Name = "Minimalist Matte Black Watch",
                            Price = 4500m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Watches",
                            Description = "Roman numerals dial layout with dark blue face accents and genuine light brown leather casing.",
                            ImageUrl = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=500",
                            Name = "Fossil Grant Chronograph Blue",
                            Price = 38000m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Watches",
                            Description = "S9 SiP processor, incredibly bright Always-On Retina display, advanced blood oxygen health sensors.",
                            ImageUrl = "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=500",
                            Name = "Apple Watch Series 9 GPS",
                            Price = 128000m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Watches",
                            Description = "Exotic fusion blend of fresh marine aquatic notes layered over dynamic woody base tones.",
                            ImageUrl = "https://images.unsplash.com/photo-1541643600914-78b084683601?w=500",
                            Name = "J. Junaid Jamshed Janan Gold",
                            Price = 6500m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Watches",
                            Description = "Highly acclaimed intense fragrance composition featuring deep black pepper and warm amber notes.",
                            ImageUrl = "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=500",
                            Name = "Lattafa Asad Premium Oud (EDP)",
                            Price = 5500m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Watches",
                            Description = "Sporty gold-toned case with durable silicone strap structure, water resistant up to 50 meters.",
                            ImageUrl = "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=500",
                            Name = "Tommy Hilfiger Sport Quartz",
                            Price = 34000m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Skincare",
                            Description = "Advanced hyperpigmentation control formula enriched with Alpha Arbutin and Vitamin C.",
                            ImageUrl = "https://images.unsplash.com/photo-1608248597481-496100c80836?w=500",
                            Name = "Jenpharm Maxdiff Brightening Serum",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Skincare",
                            Description = "Daily face wash formulated for normal to oily skin with 3 essential ceramides.",
                            ImageUrl = "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500",
                            Name = "CeraVe Foaming Facial Cleanser",
                            Price = 4200m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Skincare",
                            Description = "High-strength vitamin and mineral blemish formula that visibly targets skin congestion.",
                            ImageUrl = "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500",
                            Name = "The Ordinary Niacinamide 10%",
                            Price = 3400m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Skincare",
                            Description = "100% organic steam-distilled antibacterial essential oil ideal for acne outbreaks.",
                            ImageUrl = "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=500",
                            Name = "Saeed Ghani Pure Tea Tree Oil",
                            Price = 850m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Skincare",
                            Description = "Anti-darkening whitening cream formulation that provides high broad-spectrum UV protection.",
                            ImageUrl = "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500",
                            Name = "Rivaj UK Sun Block SPF 60",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Skincare",
                            Description = "Custom high-concentration alternative fragrance discovery collection focusing on marine notes.",
                            ImageUrl = "https://images.unsplash.com/photo-1588405748373-122b2321bc31?w=500",
                            Name = "Scents N Secrets Tester Box",
                            Price = 2800m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Skincare",
                            Description = "Oil-free skin moisturizer formulated with dynamic hyaluronic acid complex for instant hydration.",
                            ImageUrl = "https://images.unsplash.com/photo-1617897903246-719242758050?w=500",
                            Name = "Neutrogena Hydro Boost Gel Cream",
                            Price = 4800m
                        },
                        new
                        {
                            Id = 28,
                            Category = "Skincare",
                            Description = "Light-weight essence coordinates skin texturing while repairing acne scarring tissue smoothly.",
                            ImageUrl = "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=500",
                            Name = "Cosrx Advanced Snail Mucin 96",
                            Price = 5900m
                        },
                        new
                        {
                            Id = 29,
                            Category = "Skincare",
                            Description = "Micro-exfoliating treatment specialized for pore purification and blackhead extraction.",
                            ImageUrl = "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=500",
                            Name = "BBLDerma Salicylic Acid Scrub",
                            Price = 1850m
                        },
                        new
                        {
                            Id = 30,
                            Category = "Skincare",
                            Description = "Pure therapeutic organic distillate that functions as a refreshing skin toner and coolant.",
                            ImageUrl = "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500",
                            Name = "Saeed Ghani Rose Water Spray",
                            Price = 350m
                        },
                        new
                        {
                            Id = 31,
                            Category = "Fashion",
                            Description = "Classic dynamic standard indigo blue buttoned denim jacket crafted from heavy cotton.",
                            ImageUrl = "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500",
                            Name = "Engine Denim Streetwear Jacket",
                            Price = 5800m
                        },
                        new
                        {
                            Id = 32,
                            Category = "Fashion",
                            Description = "Super soft drop-shoulder fleece hoodie designed for maximum streetwear comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500",
                            Name = "Groovy Aesthetic Oversized Hoodie",
                            Price = 3800m
                        },
                        new
                        {
                            Id = 33,
                            Category = "Fashion",
                            Description = "Lightweight performance running sneakers featuring responsive memory foam insoles.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
                            Name = "Cougar Breathable Mesh Sneakers",
                            Price = 4800m
                        },
                        new
                        {
                            Id = 34,
                            Category = "Fashion",
                            Description = "Smart casual charcoal grey cotton pique polo shirt with fine stitched embroidery.",
                            ImageUrl = "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500",
                            Name = "Polo Republica Tailored Polo Shirt",
                            Price = 2400m
                        },
                        new
                        {
                            Id = 35,
                            Category = "Fashion",
                            Description = "Comfortable soft-bed genuine leather summer sliders perfect for relaxed daily wear.",
                            ImageUrl = "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500",
                            Name = "Servis Leather Casual Slides",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 36,
                            Category = "Fashion",
                            Description = "Handcrafted top-grain cowhide leather bifold card holder with secure RFID blocking layer.",
                            ImageUrl = "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500",
                            Name = "Premium Leather Bifold Wallet",
                            Price = 2200m
                        },
                        new
                        {
                            Id = 37,
                            Category = "Fashion",
                            Description = "Sophisticated mens scent projecting absolute luxury through patchouli and cedarwood extracts.",
                            ImageUrl = "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500",
                            Name = "Edenrobe Royal Woody Fragrance",
                            Price = 4200m
                        },
                        new
                        {
                            Id = 38,
                            Category = "Fashion",
                            Description = "Combed luxury organic cotton crewneck t-shirt featuring double-stitched durability standard.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500",
                            Name = "Fabriano Premium Cotton Tee",
                            Price = 1650m
                        },
                        new
                        {
                            Id = 39,
                            Category = "Fashion",
                            Description = "Multi-pocket durable cotton twill construction engineered for utility active outerwear usage.",
                            ImageUrl = "https://images.unsplash.com/photo-1517423738875-5ce310acd3da?w=500",
                            Name = "Urban Cargo Tactical Pants",
                            Price = 3400m
                        },
                        new
                        {
                            Id = 40,
                            Category = "Fashion",
                            Description = "Full protective polarized metallic framing structure sporting sleek gradient midnight lenses.",
                            ImageUrl = "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500",
                            Name = "Classic Aviator UV400 Sunglasses",
                            Price = 2900m
                        },
                        new
                        {
                            Id = 41,
                            Category = "Automotive",
                            Description = "Built-in GPS, 1944P Ultra HD resolution camera system featuring night vision clarity.",
                            ImageUrl = "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?w=500",
                            Name = "70mai Dash Cam Pro Plus A500S",
                            Price = 18500m
                        },
                        new
                        {
                            Id = 42,
                            Category = "Automotive",
                            Description = "Portable handheld car cleaning spray gun featuring adjustable nozzle patterns.",
                            ImageUrl = "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=500",
                            Name = "Baseus Car High Pressure Washer",
                            Price = 12500m
                        },
                        new
                        {
                            Id = 43,
                            Category = "Automotive",
                            Description = "Compact high-suction 5000Pa handheld mini vacuum designed for rapid car cleaning.",
                            ImageUrl = "https://images.unsplash.com/photo-1563720223185-11003d516935?w=500",
                            Name = "Baseus Car Wireless Vacuum Cleaner",
                            Price = 6800m
                        },
                        new
                        {
                            Id = 44,
                            Category = "Automotive",
                            Description = "Ultra-thick lint-free 800GSM scratchless drying cloths optimal for wax application.",
                            ImageUrl = "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=500",
                            Name = "Premium Microfiber Towels (4-Pack)",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 45,
                            Category = "Automotive",
                            Description = "Wireless dual USB fast dashboard charger allowing seamless audio transmission streams.",
                            ImageUrl = "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=500",
                            Name = "Baseus Bluetooth FM Transmitter",
                            Price = 2400m
                        },
                        new
                        {
                            Id = 46,
                            Category = "Automotive",
                            Description = "Heavy-duty N52 neodymium magnetic dashboard air vent grip securing smartphones firmly.",
                            ImageUrl = "https://images.unsplash.com/photo-1584438784894-089d6a128f3e?w=500",
                            Name = "Universal Magnetic Car Phone Mount",
                            Price = 1150m
                        },
                        new
                        {
                            Id = 47,
                            Category = "Automotive",
                            Description = "True HEPA carbon filter capturing bad odors, fine pollen, smoke particles, and dust.",
                            ImageUrl = "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=500",
                            Name = "Car Air Purifier Ionizer Ozonator",
                            Price = 4200m
                        },
                        new
                        {
                            Id = 48,
                            Category = "Automotive",
                            Description = "Backlit digital LCD precision display nozzle metering active diagnostic tire health indicators.",
                            ImageUrl = "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500",
                            Name = "Digital Tire Pressure Gauge 150PSI",
                            Price = 1850m
                        },
                        new
                        {
                            Id = 49,
                            Category = "Automotive",
                            Description = "Orthopedic lumbar spinal support pillow optimizing seat alignment for exhaustive commutes.",
                            ImageUrl = "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=500",
                            Name = "Ergonomic Memory Foam Car Cushion",
                            Price = 3800m
                        },
                        new
                        {
                            Id = 50,
                            Category = "Automotive",
                            Description = "Heavy duty flocked PVC travel bed accommodating back seat sleeping requirements effortlessly.",
                            ImageUrl = "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=500",
                            Name = "Multipurpose Inflatable Car Mattress",
                            Price = 7500m
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
